# permissions for end users to view kubeflowjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflowjob-viewer-role
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - kubeflowjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - kubeflowjobs/status
  verbs:
  - get
