
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - kubeflowjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - kubeflowjobs/finalizers
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - kubeflowjobs/status
  verbs:
  - get
  - patch
  - update
